import type {NextPage} from "next";
import Head from "next/head";
import {signIn, signOut, useSession} from "next-auth/react";
import {Button, Center, Container, Flex} from "@chakra-ui/react";
import UserProfile from "../components/user-profile";
import UserTweets from "../components/user-tweets";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<Flex mt={64} flexDirection={"column"} justifyContent={"space-between"} h={64}>
				<Container>
					<Center>
						<AuthShowcase/>
					</Center>
				</Container>

				<Container>
					<UserProfile/>
					<UserTweets/>
				</Container>
			</Flex>
		</>
	);
};

export default Home;

const AuthShowcase: React.FC = () => {
	const {data: sessionData} = useSession();

	return (
		<div>
			{sessionData && <p>Logged in as {sessionData?.user?.name}</p>}

			<Button
				mt={4}
				onClick={sessionData ? () => signOut() : () => signIn("discord")}
			>
				{sessionData ? "Sign out" : "Sign in"}
			</Button>
		</div>
	);
};

type TechnologyCardProps = {
	name: string;
	description: string;
	documentation: string;
};
